# REPRESENTATION CONSTRUCTION
# Recurrence graph
distance: cosine  # distance metric to use for recurrence graph
recwidth: 9  # only link neighbors in recurrence graph if their distance is less than recwidth
recsmooth: 9  # median filter size for recurrence matrix (try reducing if segmentation is
              # innacurate around expected segment borders)
evecsmooth: 9  # median filter size for eigenvector smoothing
mu: 0.5  # harmonic/timbral mix weight
gamma: 0.5  # deep similarity feature/CQT mix weight
# Hierarchical segmentation
n_levels: 12  # segmentation levels, int for fixed, "dynamic" for analysis till a 
              # level with a single measure is found. If no rearrangement solutions
              # are found, try setting to "dynamic" (although it might sometimes
              # require more computation time).
min_seg_size: 1  # minimum segmentation duration in measures, if not 1 uses Salamon
                 # et al.'s segment fusion algorithm
min_measure: 1  # default measure number for segmentation quantization

# CROSS-SEGMENT TRANSITION-POINT IDENTIFICATION
cross_pattern_length: 2  # minimum diagonal length to be a candidate pattern
cross_pattern_percentile: 50  # connectivity strength threshold for candidate pattern selection

# INTRA-SEGMENT TRANSITION-POINT IDENTIFICATION
intra_pattern_length: 2  # minimum diagonal length to be a candidate pattern
intra_levels_list: [2, 3, 4, 5, 6]  # levels to search for intra-segment connections

# PATH FINDING
transition_types: ideal  # ideal: only between points with rank=1
                         # nonnegative: only foward transitions
                         # all: all transitions
path_finding_algorithm: less_transitions  # greedy search for up to 3 transitions

# AUDIO RECONSTRUCTION
crossfade: 0.1  # crossfade duration in seconds for transitions